### ISSUE TITLE
Don't display 'Terminal' field if PowerShell version is less than v6

### ISSUE THREAD

**Issue by kiedtl** [lptstr/winfetch#12]
Terminal section is null:

![image](https://user-images.githubusercontent.com/32681240/56854798-53ead880-690a-11e9-9939-cf5d634dc4a1.png)

**Comment by kiedtl** [comment]
Aha, this is due to Powershell being v5 instead of v6. In which case the Terminal value should be something like "???".

**Comment by mrngstr-labs** [comment]
Same problem with Microsoft Terminal. If i change version of Powershell to PS Core 6 this is solve the problem?
![winfetch bug report](https://user-images.githubusercontent.com/34179728/80349988-bf96b700-8878-11ea-951b-c7440617079d.png)

**Comment by jcwillox** [comment]
This is technically fixed in PR #31; the terminal field will now display as `Terminal: Unknown` for versions before PowerShell 6. However, if you wanted the terminal field to not render then changing the `info_terminal` function to return `$null` or `$false` would cause it to not render.
