### ISSUE TITLE
Powershell Gallery

### ISSUE THREAD

**Issue by spacecowgirl314** [lptstr/winfetch#13]
Can you upload this to Powershell Gallery so I can install it with "Install-Module winfetch"?

**Comment by kiedtl** [comment]
Sounds like a good idea. However, I don't have time to do this at the moment.

You could either install it manually (see the wiki) or create a PowerShell package yourself. If you did that would definitely be appreciated. :grinning:

**Comment by cybercatgurrl** [comment]
Thanks, I'd appreciate that.

**Comment by rashil2000** [comment]
As a temporary measure, I have published the script using my personal account for the time being. It can be installed by: 

```powershell
Install-Script -Name pwshfetch-test-1
Set-Alias winfetch pwshfetch-test-1    # Put this in $PROFILE
```

**Comment by jcwillox** [comment]
I've written a Github action to publish PowerShell scripts to the PowerShell Gallery [jcwillox/action-publish-powershell-script](https://github.com/jcwillox/action-publish-powershell-script).
I've also created a [workflow](https://github.com/lptstr/winfetch/blob/publish-psgallery/.github/workflows/release.yaml) to publish winfetch to PSGallery, I tested it with a copy of the winfetch repo and it works.

Currently, we're only missing the `PSGALLERY_KEY`, either @kiedtl can add his own key, or I can create a Microsoft account for winfetch and provide kiedtl with the credentials, as well as the API key for him to add to the repo.

The last thing is the name `lptstr-winfetch`, `pwshfetch` or `other`?

**Comment by rashil2000** [comment]
I'd stress again on `lptstr-winfetch` - it's quite self-explanatory, and we won't have to rename any of our scripts.

**Comment by jcwillox** [comment]
We wouldn't need to rename anything, but yeah I agree that's a good choice and is much less ambiguous compared to the others.

**Comment by rashil2000** [comment]
https://www.powershellgallery.com/packages/winfetch
