### ISSUE TITLE
Ability to configure order (and add spaces)

### ISSUE THREAD

**Issue by AdrianoCahete** [lptstr/winfetch#16]
Today you just have the option to show/hide some info, but keep track of order in config file will be awesome!

Plus, the space thing will be good, because if you remove a lot of info, the info and the logo are misaligned:
![image](https://user-images.githubusercontent.com/37474/69352270-65575180-0c5b-11ea-821d-6a548c1d6bf5.png)

Config:
```
# ===== WINFETCH CONFIGURATION =====

# Remove the '#' from any of the lines in
# this file to **enable** their output.

@(
    'None'
    'None'
    'None'
    'Show_CPU'
     'Show_GPU'
     'Show_Memory'
     'Show_Disk'
     'Show_OS'
     'Show_Uptime'
     'Show_Terminal'
     'Show_Pwsh'
#    'Show_Title'
#    'Show_Dashes'    
#    'Show_Computer'    
#    'Show_Pkgs'    
) -join ','

```

**Comment by rashil2000** [comment]
@kiedtl this can be closed now, right?

**Comment by kiedtl** [comment]
Yeah, I believe it can be.
