### ISSUE TITLE
Transfer repository to an organization

### ISSUE THREAD

**Issue by kiedtl** [lptstr/winfetch#162]
This repository was moved from @lptstr last year as I cleaned up that pseudo-organization (which was basically my personal playground for "serious" projects) (see #81).

After some thought and discussion with @rashil2000, I think it'd be best to move the repo back to an organization, for several reasons:

- Multiple maintainers can have admin roles, and thus manage the repo's topics/descriptions and perform other admin-only actions.
- I'm barely looking at the repo once a month, so I feel it's slightly unfair to imply that I'm the current maintainer by continuing to keep it under my personal account.
- My GitHub feed won't be spammed anymore with multiple `InactivitiusMaximum starred two repositories [Winfetch ...]` daily.
- Bus factor etc.

At this point, we could move the repo back to @lptstr, but I'm wondering if it's better just to create another "winfetch" organization for the sole purpose of hosting this repo.

EDIT: Hm, someone already created a `winfetch` user 😅

**Comment by kiedtl** [comment]
Checklist for transferring repository:

- [ ] Updating README
- [ ] `winfetch.ps1` metadata
- [ ] Chocolatey package
- [ ] Scoop package
- [ ] wiki

Not that there's a hurry, GitHub will continue to redirect URLs for some time...

**Comment by rashil2000** [comment]
> EDIT: Hm, someone already created a `winfetch` user 😅

`winfetch-git` (name of PSGallery package, basically) is still untaken. I can create it if that's good with you.

**Comment by kiedtl** [comment]
I've contacted the owner of the winfetch org. If they don't respond by next week I think we'll go ahead with using `lptstr`.

**Comment by kiedtl** [comment]
I was unable to reach the winfetch org owner, so I've transferred the repo to `lptstr`.

**Comment by rashil2000** [comment]
Hmm but admin role still needs to be enabled for this repo (at least for me - I'm not admin yet).

**Comment by kiedtl** [comment]
Yes, I was waiting on your pending invitation to the GitHub org. I've given you an Admin role now.

**Comment by rashil2000** [comment]
Alright, thanks so much! I'll get to the rest of the checklist stuff as soon as I get time.

**Comment by jakublevy** [comment]
Chocolatey package updated: https://github.com/jakublevy/chocopkgs/commit/820b9dfb0b45ef4b0a094bf8911e02a7411f04fe
You can check it the checklist.

**Comment by rashil2000** [comment]
New release! https://github.com/lptstr/winfetch/releases/tag/v2.5.0
