### ISSUE TITLE
Winfetch won't run when I type winfetch

### ISSUE THREAD

**Issue by Dhyfer1** [lptstr/winfetch#168]
Hi.

I installed Winfetch through the recommended way, using Powershell Gallery. I followed the instructions mentioned in Installation, so to start I typed the following in Powershell:

```
Install-Script -Name pwshfetch-test-1
Set-Alias winfetch pwshfetch-test-1    # Put this in $PROFILE
```

After an installation without any apparent problem, I type winfetch and it runs correctly, then I close Powershell.
When I reopen Powershell to run winfetch again, this is the error message after typing winfetch:

```
PS C:\Users\diego> winfetch
winfetch : The term 'winfetch' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ winfetch
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (winfetch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

However, winfetch runs correctly if I type the name of the script, which is pwshfetch-test-1

What can I do to make winfetch run just by typing winfetch?

Thanks in advance.

**Comment by rashil2000** [comment]
Run this:
```pwsh
New-Item $PROFILE -Force
Add-Content $PROFILE 'Set-Alias winfetch pwshfetch-test-1'
```
Now it should work.

**Comment by Dhyfer1** [comment]
> Run this:
> 
> ```powershell
> New-Item $PROFILE -Force
> Add-Content $PROFILE 'Set-Alias winfetch pwshfetch-test-1'
> ```
> 
> Now it should work.

Thank you very much, now it works! 😁 But I think those commands should also be mentioned in the wiki when winfetch is installed from Poweshell Gallery, don't you think?

**Comment by rashil2000** [comment]
Users of PowerShell already have the `$PROFILE` file created, so the command to create it is not mentioned.
