### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by kiedtl** [lptstr/winfetch#17]
Since I rarely use Windows anymore, I'm looking for an additional maintainer.

**Comment by Dools1337** [comment]
Since I'm forced to use windows, I for one would like to thank you for your effort. : )

**Comment by ppadial** [comment]
I'm a bit late to the party. I can help as maintainer, I don't have tons of time but i can organise myself to carry on with some stuff.

**Comment by ppadial** [comment]
I'll fork tomorrow and do some of the tickets, the one about memory and the one to publish to psgallery with my account.

**Comment by kiedtl** [comment]
> the one to publish to psgallery with my account.

Thanks!

**Comment by kiedtl** [comment]
> should I maintain my own fork?

I'd strongly prefer that all development be done here, in this repository.

I'm planning the get back to winfetch development next week, by the way.

> i guess if you make me a contributor of this repo, i can collaborate with closing issues, etc, and we can keep this repo alive.

No problem. Just submit your contributions, and I'll eventually add you as a contributor.

> By other hand, i had to rename the script to posh-winfetch to publish as you can see here: #13 makes sense to rename this repo to posh-winfetch?

I just don't see the point of renaming the project simply because we were unable to get the name we wanted on the PowerShell gallery. I don't think it's that big of an issue if the PowerShell script has a slightly different name than the project name. We just need to ensure this is documented properly, to prevent users from accidentally downloading the wrong package.

> The only limitation is that i need to publish each module version using my own jenkins at home, but it's fine for me.

I'm fine with that.

**Comment by kiedtl** [comment]
@ppadial

**Comment by ppadial** [comment]
Ok!

**Comment by ppadial** [comment]
Hi @kiedtl , due some issues, I cannot maintain the update on powershell gallery using my infra anymore.
Do you want to take the ownership of that package ? I can transfer it to you (or to another volunteer), just give me your powershell gallery user.

Otherwise, I would recommend to PR and replace the indications to install from the main README in section Quick Usage, since, it will get an old version always, and that's not good for all the effort people is doing on PR updates to the script.

**Comment by kiedtl** [comment]
@jcwillox @rashil2000 Considering that I can't even look at the latest bugs/feature requests filed, much less take a look at the current pull requests, would you two consider taking over development of Winfetch? I can give both of you maintainer access to the repository, and just leave the project to you. At that point, I'll just step away[0] from the project (though I may occasionally comment and make suggestions on PRs/issues).

[0]: until I'm forced to use Winblo-I mean, Windows again.

**Comment by jcwillox** [comment]
@kiedtl Hahah, I was just going to say that'd I'd be happy for you to add me as a maintainer, either way, I'll continue to help maintain winfetch to whatever extent I can, obviously the ability to merge PRs and create releases would help.

**Comment by rashil2000** [comment]
@kiedtl That sounds like a plan! I'd be happy to review PR's and merge commits.

**Comment by kiedtl** [comment]
@jcwillox @rashil2000 I've given both of you access to this repository.

Good luck! :^)

**Comment by jcwillox** [comment]
@kiedtl thanks, I'll do my best!

Do you know what's happening with the `Codacy/PR Quality Review` it doesn't appear to be working, and is preventing me from merging PRs through Github?

**Comment by rashil2000** [comment]
Thanks @kiedtl!

@jcwillox let's add a couple of Milestones and use the Discussions tab to discuss possible new additions.

**Comment by jcwillox** [comment]
@rashil2000 great idea, I intend to create a new major release (2.0.0) which will include the new configuration method, I'll release that once the issue with merging the remaining PRs is resolved.

**Comment by kiedtl** [comment]
I have no idea. I'll take a look at that later today and remove the
Codacy garbage.

**Comment by kiedtl** [comment]
Should be fixed.
