### ISSUE TITLE
Windows logo overlapping with text

### ISSUE THREAD

**Issue by NavTech270** [lptstr/winfetch#171]
![Windows_Overlapped](https://user-images.githubusercontent.com/62112451/208250135-2ad4e279-8c74-4235-99cf-4b448a848255.png)

Not sure why this is happening. When the "blink" setting is set to true in the config, the windows logo size is set properly:

![image](https://user-images.githubusercontent.com/62112451/208250096-49aa02c7-5f1c-49ab-a9ec-ad29a5b6e676.png)

**Comment by rashil2000** [comment]
That's odd. Which terminal and font are you using?

**Comment by NavTech270** [comment]
Terminal I'm using is Windows Terminal running Powershell. I'm using a nerd font called "Hurmit NF" @rashil2000

**Comment by rashil2000** [comment]
Paste the link to:
- your winfetch config file
- your terminal config file
- where you downloaded the font from

Also, which version of winfetch are you using?

**Comment by kiedtl** [comment]
Maybe I'm wrong, but it seems like the font is overlapping other text? If so this would be an issue with the Windows Terminal. You don't happen to be running the Preview, are you?

**Comment by NavTech270** [comment]
I'll test with a different font and see if the same thing happens @kiedtl

**Comment by NavTech270** [comment]
Turns out the font, "Hurmit NF" from Nerd Fonts is the problem. Not sure why but I tried using another font, "Cascadia Code" and it worked perfectly. Very strange behaviour; bit sad you can't use "Hurmit NF" without "$blink=$true". @kiedtl @rashil2000

**Comment by rashil2000** [comment]
Hmm, patched nerd fonts are not always reliable - I can say this from experience 😅

Closing this as external...
