### ISSUE TITLE
Winfetch Config problems

### ISSUE THREAD

**Issue by AlexTheOutsider22** [lptstr/winfetch#173]
![image](https://user-images.githubusercontent.com/103733984/214012337-eb39bfdc-1fed-451b-bb69-f335130b977f.png)
I've tried configuring Winfetch itself, but for some reason it doesnt apply, and Im not that knowledgeable to know whats wrong.
same with PowerShell 5

**Comment by rashil2000** [comment]
You need to edit the config file, not the source powershell script. The config file is at C:\Users\crsdv\.config\winfetch\config.ps1

**Comment by AlexTheOutsider22** [comment]
Hello Rashil2000! thank you so much! helped a lot!

**Comment by rashil2000** [comment]
No worries :)

**Comment by AlexTheOutsider22** [comment]
![image](https://user-images.githubusercontent.com/103733984/216381655-8d456916-8bc5-4f42-8260-db236fce6cb7.png)
This is how it looks on my windows 10 machine after configuring it, sure will do on 11 too. does it have ASCII images like Fedora, Ubuntu, etc.?

**Comment by rashil2000** [comment]
You can put any image you want in the config file: https://github.com/lptstr/winfetch/wiki/Configuration

**Comment by AlexTheOutsider22** [comment]
oh yea, im dumb, just saw the image entry in the config file
