### ISSUE TITLE
CPU Usage keep showing 0%

### ISSUE THREAD

**Issue by azmankudus** [lptstr/winfetch#185]
Hi, after i enabled "cpu_usage", it keep showing zero eventhough task manager shows non-zero.

![image](https://user-images.githubusercontent.com/25720114/232278129-95025004-204a-424f-b289-3ad18426c650.png)

**Comment by rashil2000** [comment]
Winfetch shows instantaneous CPU usage - i.e. it is measured in a very short time interval. 

It is roughly equivalent to what is shown in the Task Manager, but they will not always match exactly.
