### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by bckelley** [lptstr/winfetch#186]
If you install it exactly as stated in the wiki this doesn't work only way I can get this to run is by using the full path ``` .local\bin\winfetch.ps1 ```

**Comment by helpimnotdrowning** [comment]
My workaround is to put this into your `$PROFILE`:
```pwsh
Set-Alias -Value C:\Path\To\winfetch.ps1 -Name Winfetch
```
and use `Winfetch` to run it.

**Comment by rashil2000** [comment]
> If you install it exactly as stated in the wiki this doesn't work only way I can get this to run is by using the full path `.local\bin\winfetch.ps1`

The folder `.local\bin` needs to be in your PATH. Or you can move the script to a location that's already present in PATH environment variable.
