### ISSUE TITLE
`clist` deprecated in chocolatey v2

### ISSUE THREAD

**Issue by aetonsi** [lptstr/winfetch#189]
Hi,
chocolatey v2 is now available. One of its breaking changes is:
> Remove deprecated Chocolatey shims (chocolatey, cinst, clist, cpush, cuninst, cup) - see [#2642](https://github.com/chocolatey/choco/issues/2642).

and also
> Change behavior of choco list to be local only - see [#158](https://github.com/chocolatey/choco/issues/158).

So both `clist <anything>` and `choco list -lo` don't work anymore.

The command is simply `choco list` now.
A check with `choco --version` is needed i think, because if i'm not mistaken `choco list` without arguments also includes remote packages, in choco v1

---

have a nice day

**Comment by rashil2000** [comment]
What's the behaviour when we type `choco list -l` in Chocolatey v2?

**Comment by AlexKari** [comment]
this is easily fixed by substituting the line 875
`$chocopkg = (& clist -l)[-1].Split(' ')[0] - 1`
with this
`$chocopkg = (& choco list)[-1].Split(' ')[0] - 1`

**Comment by aetonsi** [comment]
> What's the behaviour when we type `choco list -l` in Chocolatey v2?

```log
> choco list -l
Chocolatey v2.0.0
Invalid argument -l. This argument has been removed from the list command and cannot be used.
```



> this is easily fixed by substituting the line 875 `$chocopkg = (& clist -l)[-1].Split(' ')[0] - 1` with this `$chocopkg = (& choco list)[-1].Split(' ')[0] - 1`

`choco list` without `-lo` in chocolatey v1 lists all of the available packages (uses remote sources), not the locally installed ones

```log
> choco list
Chocolatey v1.4.0
Using the list command with remote sources is deprecated and will be made
to only list locally installed packages in v2.0.0. Use the search, or find,
command to find packages on remote sources (such as the Chocolatey Community
Repository).
cpfixit 5.0.16772.0 [Approved] Downloads cached for licensed users
git-sizer 1.5.0 [Approved]

...

jackett 0.21.128 [Approved]
6805 packages found.

Did you know Pro / Business automatically syncs with Programs and
 Features? Learn more about Package Synchronizer at
 https://chocolatey.org/compare
```

**Comment by justin13888** [comment]
I'm using chocolatey 2.0.0 and I don't have clist command in path.

**Comment by aetonsi** [comment]
because it doesn't exist anymore

**Comment by SliceTheDuck** [comment]
this has been fixed in april just never pushed to scoop etc.

**Comment by audacenoire** [comment]
Do I have to fix the source code manually until the new version is pushed?

**Comment by SliceTheDuck** [comment]
You could build it from the repo or replace it yes, once you replaced it unless you updated or redownload it(when you compile yourself this ain't Gon happen) it stays fixed

**Comment by audacenoire** [comment]
`InvalidArgument: C:\tools\winfetch\winfetch.ps1:875
Line |
 875 |          $chocopkg = (& choco list -l)[-1].Split(' ')[0] - 1
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert value "Invalid" to type "System.Int32". Error:
     | "The input string 'Invalid' was not in a correct format." `
     
    I  get this error when I try to fix the code manually.

**Comment by tordenflesk** [comment]
> ```
> InvalidArgument: C:\tools\winfetch\winfetch.ps1:875
> Line |
>  875 |          $chocopkg = (& choco list -l)[-1].Split(' ')[0] - 1
>      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot convert value "Invalid" to type "System.Int32". Error:
>      | "The input string 'Invalid' was not in a correct format." 
> ```
> 
> I get this error when I try to fix the code manually.

Remove the -l

**Comment by Windos** [comment]
There is a PR open (#191) regarding the `-l`/`--local-only` option.

I've suggested a change to that PR which will solve the syntax difference between Chocolatey CLI 2.x and prior versions.

**Comment by rashil2000** [comment]
It would be helpful if y'all could help test PR #191

**Comment by tordenflesk** [comment]
> sure @rashil2000 , could you explain how do i download the modified code? sorry i'm not too practical yet with PRs and things

https://raw.githubusercontent.com/lptstr/winfetch/cc3830a61f445964a9c02192579205f2608fa76a/winfetch.ps1

**Comment by aetonsi** [comment]
working without any problem in win11 + [choco v1 OR choco v2] + [pwsh7 OR powershell5]
so i tested everything for win11. i do not have win10

**Comment by aetonsi** [comment]
@rashil2000 hi i just got this result, any idea why `choco` packages might be `-1`? unluckily i closed the window right away so i have no info about the problem, and i cannot reproduce it...

(the `show-winfetch` function is still the same as here https://github.com/lptstr/winfetch/issues/181#issue-1639177758 plus `-logo 'windows xp'` and `'winget'` added to the `showpkgs` list)

```
> Show-Winfetch
         ,.=:!!t3Z3z.,                 u6@NOTEBOOK3W
        :tt:::tt333EE3                 -------------
        Et:::ztt33EEE  @Ee.,      ..,  OS: Windows 11 Pro N [64-bit]
       ;tt:::tt333EE7 ;EEEEEEttttt33#  Host: HP HP Pavilion Laptop 15-eh0xxx
      :Et:::zt333EEQ. SEEEEEttttt33QL  Kernel: 10.0.22631.0
      it::::tt333EEF @EEEEEEttttt33F   Motherboard: HP 87C5
     ;3=*^```'*4EEV :EEEEEEttttt33@.   Uptime: 4 hours 13 minutes
     ,.=::::it=., ` @EEEEEEtttz33QF    Resolution: 1536x864, 1920x1080
    ;::::::::zt33)   '4EEEtttji3P*     PS Packages: 6 Modules
   :t::::::::tt33 :Z3z..  `` ,..g.     Packages: 230 (system), -1 (choco), 7 (scoop)
   i::::::::zt33F AEEEtttt::::ztF      Shell: PowerShell v7.3.7
  ;:::::::::t33V ;EEEttttt::::t3       Terminal: Windows Terminal

...
```

**Comment by rashil2000** [comment]
I don't know for sure, on top of my head. Let me know if it occurs again

**Comment by ariyako** [comment]
can confirm this still not solve on Windows 10

**Comment by rashil2000** [comment]
> can confirm this still not solve on Windows 10

How did you install winfetch?
