### ISSUE TITLE
Winfetch should display memory as "used / total" instead of "available / total"

### ISSUE THREAD

**Issue by ghost** [lptstr/winfetch#19]
The RAM usage in winfetch displays incorrectly.
![QkZOLFthNF](https://user-images.githubusercontent.com/52718434/75110665-d6adf400-55fe-11ea-8ada-fc8f0ece5cb7.png)

**Comment by billbatista** [comment]
Isn't it correct? Winfetch shows 28GB available of 32GB total, same as task manager. The difference maybe would be that winfetch is displaying the results in megabytes and, for instance on my machine, instead of showing 16GB it shows 15GB.

**Comment by mater11234** [comment]
Yeah I didn't really know that Windows displays memory usage like `28839MiB / 32710MiB`. I expected it to display like `3,871MiB / 32710MiB` as Unix-like OSes do so.

**Comment by kiedtl** [comment]
This is still an issue with winfetch. Unless there's something really wrong with my eyes `28839MiB` is `28GiB`.
