### ISSUE TITLE
CmdletBinding error on line 70 (Windows 10/11) 

### ISSUE THREAD

**Issue by audacenoire** [lptstr/winfetch#190]
So I'm attempting to build from source to update `clist` >> `choco list`, but when I run the new script, I get the following error: 

`
ParserError: C:\Users\Audie\Downloads\winfetch-2.5.0\winfetch.ps1:70
Line |
  70 |  [CmdletBinding()]
     |  ~~~~~~~~~~~~~~~~~
     | Unexpected attribute 'CmdletBinding'
`

I attempted this on two computers running Windows 10 and 11, with the same effect.

**Comment by SliceTheDuck** [comment]
I am unable to reproduce the bug, any specific steps to reproduce?

**Comment by audacenoire** [comment]
> I am unable to reproduce the bug, any specific steps to reproduce?

1. Download winfetch-2.5.0 from releases page and unzip into any directory
2. Open a PowerShell prompt, cd to the directory containing the winfetch.ps1 file 
3. Run `./winfetch.ps1`

**Comment by bburt91** [comment]
Can confirm on Win11 (installed via Scoop). Unable to replicate on Win10, also installed via Scoop.


![winfetcherror](https://github.com/lptstr/winfetch/assets/90598163/805752ce-596a-4b78-bdb7-3fcb1ad9798b)

**Comment by rashil2000** [comment]
Discussion is here at #189
