### ISSUE TITLE
Issue with clist command, line 875

### ISSUE THREAD

**Issue by cmdshft** [lptstr/winfetch#192]
![image](https://github.com/lptstr/winfetch/assets/8571823/0debdd88-0127-45fd-822a-5962dbbaeab0)

**Comment by majvax** [comment]
there is an easy workaround, firstly gen a new config (`winfetch -genconf`) and edit your config with any text editor. At the bottom, comment "pkgs" and save the file. winfetch can be run again without any error

**Comment by SeryiBaran** [comment]
Me helps change line 875 to `$chocopkg = [convert]::ToInt32((& choco list)[-1].Split(' ')[0], 10) - 1`

**Comment by SeryiBaran** [comment]
Oh, I could look into #191

**Comment by Keshav13142** [comment]
Turns out `clist` was [deprecated](https://github.com/chocolatey/choco/issues/2641) by chocolatey.
So I just created an alias in my powershell profile.
```ps1
function clist { choco list }
```

**Comment by SeryiBaran** [comment]
> Turns out `clist` was [deprecated](https://github.com/chocolatey/choco/issues/2641) by chocolatey. So I just created an alias in my powershell profile.
> 
> ```powershell
> function clist { choco list }
> ```

omg, you genius! thanks (but i'm disable package showing)!

**Comment by Keshav13142** [comment]
> omg, you genius! thanks (but i'm disable package showing)!

Yes, I also did the same, both chocolatey and winget take a good 1-2 sec to list the package on my laptops.

**Comment by rashil2000** [comment]
Duplicate of #189
