### ISSUE TITLE
Help with the weather info

### ISSUE THREAD

**Issue by oneeyedreaper** [lptstr/winfetch#196]
### Discussed in https://github.com/lptstr/winfetch/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **oneeyedreaper** July 28, 2023</sup>
The displayed weather info in winfetch is incorrect. Can someone please help me with it? I'm not sure what I'm doing wrong.</div>

**Comment by rashil2000** [comment]
Continued in #195
