### ISSUE TITLE
Support better image display

### ISSUE THREAD

**Issue by hungpham3112** [lptstr/winfetch#198]
Currently, it seems winfetch only support 8 bit image and therefore it's kinda ugly when display to screen
Original:
![pikachu](https://github.com/lptstr/winfetch/assets/75968004/c6ea0b86-2774-4faf-b5d5-8470e1cd3821)

Winfetch:
![image](https://github.com/lptstr/winfetch/assets/75968004/1fca1e61-7ff0-4f9d-bb30-c885e5b6209e)

**Comment by rashil2000** [comment]
No terminal emulators on Windows support displaying images as is, currently. They have to be approximated by box-like characters. 
So this is out of scope for now.
