### ISSUE TITLE
Weather - Show Emojis

### ISSUE THREAD

**Issue by f1refa11** [lptstr/winfetch#199]
Like: 
```
Weather:🌥18°C - Partly cloudy
```

**Comment by oneeyedreaper** [comment]
I was facing some issues with the weather section some days ago and was suggested to create a custom section and make it however you like.
For your specific request, something like this should work:
`function custom_weather {
    return @{
        title = "Weather"
        content =try {
            (Invoke-RestMethod wttr.in/?format="%c%t+-+%C").Replace("+","")
        } catch {
            "$e[91m(Network Error)"
        }
    }
`
You can play around the the format based on these [docs](https://github.com/chubin/wttr.in)

**Comment by rashil2000** [comment]
Some terminals have trouble showing emojis - so we opt for wider compatibility here. 

However, as @oneeyedreaper mentioned, you can create a custom weather segment in the config file to show the emojis.
