### ISSUE TITLE
cmder/conemu: Color bar doesn't reset, so windows logo has a white stripe

### ISSUE THREAD

**Issue by r15ch13** [lptstr/winfetch#2]
Color bar doesn't reset, so windows logo has a white stripe. Only in Cmder/Conemu

![cmder](https://user-images.githubusercontent.com/432127/55561467-7f571a80-56f2-11e9-9027-96839cea3c69.png)

![pwsh](https://user-images.githubusercontent.com/432127/55561721-f4c2eb00-56f2-11e9-9f18-548eb64f599d.png)

**Comment by kiedtl** [comment]
thanks for reporting! I'll fix this in a moment...

**Comment by kiedtl** [comment]
fixed in 85007b37788b9459199c7f780cb977308f37e4fc
