### ISSUE TITLE
Neofetch faster than winfetch with default settings

### ISSUE THREAD

**Issue by vvirtues** [lptstr/winfetch#204]
I did 5 different benchmarks using hyperfine to compare them, and each time neofetch was faster. Both are at their defaults and i used `-w 3` to warm them up. Is this true?

**Comment by vvirtues** [comment]
might be just me, but at default settings, fastfetch destroys the competition
![image](https://github.com/lptstr/winfetch/assets/81705406/4130132b-1f5f-40f8-a823-e969e0512be0)

**Comment by CarterLi** [comment]
That was because the powershell interpreter was started and stoped in every run

**Comment by rashil2000** [comment]
Winfetch will be slower if you run it outside of PowerShell. It needs to initialize the .NET runtime during startup. The benchmarks assume this cost to be absent.
