### ISSUE TITLE
Terminal info is incorrect when installed with scoop and run under wezterm terminal and git bash shell

### ISSUE THREAD

**Issue by ykhan21** [lptstr/winfetch#206]
When installed with scoop and run under the wezterm terminal and the git bash shell, winfetch displays the terminal name as "sh" instead of "wezterm-gui". This occurs when running winfetch normally, by entering "winfetch" in the shell.
However, when running winfetch in the same environment but as: `pwsh -noprofile -file ~/scoop/apps/winfetch/current/winfetch.ps1`, then the terminal is displayed correctly, as "wezterm-gui".

**Comment by rashil2000** [comment]
Oh, I somehow missed adding `sh` to this array. 

https://github.com/lptstr/winfetch/blob/8cf5f860d55ef1f7f4fcdc45a07a49544d065236/winfetch.ps1#L657

Would you like to fix this?

**Comment by ykhan21** [comment]
I don't mind, you can add it. Though shouldn't the shell be bash?
When I use Wezterm with the bash shell that comes with git for windows, `echo $SHELL` outputs `/usr/bin/bash`.

**Comment by rashil2000** [comment]
Bash is already present in the array. 

I've made the change: https://github.com/lptstr/winfetch/commit/8d4f687b5e212f276c63ff26f09bee218b65d9b6
