### ISSUE TITLE
Color in ascii art $CustomAscii

### ISSUE THREAD

**Issue by pwsandoval** [lptstr/winfetch#209]
From the documentation I can change default ascii with

$CustomAscii = @(
   ...
)

But how can define that the image have different colors? I tried with ANSI escape sequences, but this is scaped, and doesnt work.

**Comment by rashil2000** [comment]
You can write ANSI escape codes similar to how it's written in the script, see: https://github.com/lptstr/winfetch/blob/8d4f687b5e212f276c63ff26f09bee218b65d9b6/winfetch.ps1#L445-L541

**Comment by pwsandoval** [comment]
Thanks, I was able to customize the default "Windows" logo

![image](https://github.com/lptstr/winfetch/assets/15174704/29d0e758-d7ba-4c94-9e22-5fa620253d28)
