### ISSUE TITLE
Add weather location option

### ISSUE THREAD

**Issue by gfcwfzkm** [lptstr/winfetch#211]
The idea is, that one could add additional parameters to the wttr.in request - for example the exact town or city to get a more local weather information.

**Comment by rashil2000** [comment]
The weather segment already fetches your location from your IP: 

![image](https://github.com/lptstr/winfetch/assets/46838874/3fa1a99a-6081-4628-b35d-a07b0f6e476a)

However, if you want more fine-grained control, you can just create a custom segment in the config file very easily: https://github.com/lptstr/winfetch/wiki/Configuration#custom-info-segments
