### ISSUE TITLE
Winfetch should be compatible with PowerShell 5

### ISSUE THREAD

**Issue by kiedtl** [lptstr/winfetch#3]
Yes, PowerShell 6 is far better than PowerShell 5. However, the fact that PowerShell 6+ is required for Winfetch may be a deterrent for users to try Winfetch.

**Comment by TheIncorrigible1** [comment]
If you'd like to backport any functionality they've implemented in v6, I bet you're welcome to submit a PR.  Considering it doesn't rely on any newer APIs except the conhost upgrade from anniversary upgrade on Windows 10 (I think that's when it was introduced), it shouldn't be difficult to look through their script to get that functionality you desire.

**Comment by kiedtl** [comment]
> I bet you're welcome to submit a PR.

[I hope I am.](https://github.com/lptstr/winfetch/graphs/contributors) XD

**Comment by TheIncorrigible1** [comment]
@kiedtl Oh man I'm blind.  I thought you were a random person complaining about lack of cross-functionality.  I like this project idea enough I think I'll check it out contributing.

**Comment by kiedtl** [comment]
#6 merged, this should be fixed.
