### ISSUE TITLE
Create a chocolatey package

### ISSUE THREAD

**Issue by huntantr** [lptstr/winfetch#38]
Along with using scoop for a package manager, create a package using chocolatey as well.

**Comment by rlaPHOENiX** [comment]
+1

**Comment by jcwillox** [comment]
I'm not familiar with creating chocolately packages, if anyone can provide an example of another script that has a chocolatey package, that'd be helpful, preferably using auto-update. Before we create an official chocolatey package it needs to be able to update itself like the scoop package does, i.e. without requiring human interaction. I'm not sure how easy that is to do with chocolatey?

**Comment by rlaPHOENiX** [comment]
> 
> 
> I'm not familiar with creating chocolately packages, if anyone can provide an example of another script that has a chocolatey package, that'd be helpful, preferably using auto-update. Before we create an official chocolatey package it needs to be able to update itself like the scoop package does, i.e. without requiring human interaction. I'm not sure how easy that is to do with chocolatey?

https://docs.chocolatey.org/en-us/create/

This docs page gives you all the information you would need.

**Comment by jcwillox** [comment]
Thanks, I have of course read the chocolatey documentation, however, it does not provide any information specific to publishing scripts from Github, or how to set up unattended automatic updates. It looks like this might be possible through Github actions. As someone who has never used chocolatey or created a chocolatey package, an example of another script that is being published automatically to chocolatey would be quite helpful, as I don't want to reinvent the wheel.

**Comment by jcwillox** [comment]
This is a pretty good example https://github.com/majkinetor/au-packages

**Comment by rashil2000** [comment]
@jcwillox I think the issue is that while Chocolatey allows and has published PowerShell _modules_, it doesn't support publishing PowerShell _scripts_ (or no one has done it yet). 

I have proposed a possible solution in #67.

**Comment by rashil2000** [comment]
Ah, my bad, perhaps I didn't look hard enough. Nevertheless, #67 addresses some more stuff too.

**Comment by jakublevy** [comment]
Hello, I have just made an Chocolatey package:
https://chocolatey.org/packages/winfetch/

It is now under review.

**Comment by jakublevy** [comment]
Here's a patch file for Installation.md on wiki that adds Chocolatey as an install option.
https://gist.github.com/jakublevy/c9a5405837634a7978a7ff02beb17cf7

**Comment by rashil2000** [comment]
Wow, thanks for this!

Question: is there a way to convert it into a Chocolatey Automatic Package?

**Comment by jakublevy** [comment]
Look at my GitHub [repo](https://github.com/jakublevy/chocopkgs/tree/master/winfetch) for winfetch chocopkg.

The file [update.ps1](https://github.com/jakublevy/chocopkgs/blob/master/winfetch/update.ps1) is for [au](https://github.com/majkinetor/au).

**Comment by rashil2000** [comment]
Great, thanks again!

**Comment by jakublevy** [comment]
Good news!
winfetch choco package has just been approved.

It can now be installed by executing 
`choco install winfetch`

Future updates of winfetch will be auto updated and pushed to choco from my machine.

Don't forget to update to Installation wiki to include choco there!

**Comment by rashil2000** [comment]
The installation [instructions](https://github.com/lptstr/winfetch/wiki/Installation) have been updated.
Thanks again to @jakublevy!
