### ISSUE TITLE
Truncate long lines

### ISSUE THREAD

**Issue by rashil2000** [lptstr/winfetch#39]
Winfetch should, ideally, clip the output of a line if its length exceeds the current buffer width, just like Neofetch.

I started working on it, but I think it'll take some time, because it needs a lot of escape sequences to be handled. 

Also pinging @jcwillox for suggestions; he recommended me to open this issue here.

**Comment by jcwillox** [comment]
So I tried to get this working and had some success, however, it was not robust enough. Basically, I used this `$length = ($output -replace '\x1b\[[0-9;]*m', '').Length` to get the length of the info line without the ANSI sequences. I could then calculate the free space in the terminal window and remove characters from the right. But that assumed escape sequences would always be at the beginning, and had an issue when the terminal window was really small.

Neofetch uses the ANSI sequence `$e[?7l` to disable line wrap and `$e[?7h` to re-enable it. However, these don't really work correctly in PowerShell.

So, currently, the best option seems to be to write a function which calculates the number of printing characters then splits up a string based on ANSI escape sequences, and removes X printing characters from right, then recombines the string.

Safe to say this will take a little longer so I'm dropping this from the `v2.0.0` milestone, as I want to get that released.

**Comment by rashil2000** [comment]
Sure, that's understandable. 

When do you plan on releasing V2? I have a couple of features in the pipeline too (they're tiny ones, can be wrapped in a single PR) - as seen on #50.

**Comment by jcwillox** [comment]
I'd like to release it later this week, I was thinking maybe like Friday? The main focus of v2 is the new config, but I held off releasing it as were fixing some of the current issues and implementing a couple important features. The only other thing I want to do is improve the packages speed, after that we should be ready to release v2. Obviously, this is a major release and I wanted to make it good, after this we'll be creating new releases much more frequently. Looking at the remaining stuff in #50 there's no reason those can't come in sequent releases, I wouldn't rush to finish any of them. Ideally we want to get the ball rolling on creating releases, so it's probably best if we set a deadline to publish v2.

**Comment by rashil2000** [comment]
Speaking of deadlines, I think this weekend would be a very convenient time. The additions I mentioned are really small, but I haven't got around to committing them due to some college work. The process info part is essential I think; others can maybe wait.

**Comment by jcwillox** [comment]
Great, sounds good to me, we'll aim for this weekend 👍

**Comment by rashil2000** [comment]
Hi @jcwillox, I just pushed my PR to `master` by mistake. I used VSCode's push command and it didn't warn me :(

Anyways, just check out the changes locally, if there's a problem, I'll make a revert commit.

**Comment by jcwillox** [comment]
That's ok, most of the changes look fine, I've added comments to some of the commits

**Comment by rashil2000** [comment]
Since we definitely missed out on our initial deadline for 2.0 release, let's put this issue back in the pipeline for 2.0? I think it might be easier to deal with this now with the `stripansi` utility.

**Comment by jcwillox** [comment]
Alright, but this should be the last feature we're adding to the 2.0 release, as there's no point waiting for some perfect version of winfetch, and I think we're at a good point now supporting all the most important features. Also, those issues you just closed won't technically be solved until we release the new version. I'd like to release 2.0 tomorrow, assuming we've merged this feature by then.

I've written up a working draft, I'll try to finalise it and open a PR tonight.

**Comment by rashil2000** [comment]
Sure, sounds good 👍

**Comment by jcwillox** [comment]
@rashil2000 I've finalized the release notes, are you happy for me to release `v2.0.0`?

**Comment by rashil2000** [comment]
Looks good to go. Just a couple of points:

- The link to default configuration in the wiki, that is, https://github.com/lptstr/winfetch/blob/master/winfetch.ps1#L205 is subject to change with each commit because of the line number. Either consider using https://github.com/lptstr/winfetch/blob/v2.0.0/winfetch.ps1#L205, or consider removing the hyperlink altogether?
- Systems older than Windows 7 - NT4.0, 95/98, 2000, XP, Server 2003, Vista etc. are not compatible with PowerShell version 5 or later. We can add a small footnote to the release notes redirecting people to the legacy branch in case they're on those systems.

**Comment by jcwillox** [comment]
Yeah your probably right I'll pin it to a specific version. I've added the legacy branch to the list of new features. Looks like we're finally ready to release 2.0.
