### ISSUE TITLE
error using default config

### ISSUE THREAD

**Issue by thorstenkampe** [lptstr/winfetch#41]
```
❯ winfetch -genconf
INFO: downloading default config to 'C:\Users\thorsten\.config/winfetch/config.ps1'.
INFO: successfully completed download.

~ powershell
❯ F:\scoop\apps\winfetch\current\winfetch.ps1
winfetch.ps1: Cannot convert value "title,dashes,os,computer,kernel,uptime,pkgs,pwsh,terminal,cpu,gpu,memory,blank,colorbar" to type "Configuration". Error: "Unable to match the identifier name title,dashes,os,computer,kernel,uptime,pkgs,pwsh,terminal,cpu,gpu,memory,blank,colorbar to a valid enumerator name. Specify one of the following enumerator names and try again:
None, Show_Title, Show_Dashes, Show_OS, Show_Computer, Show_Uptime, Show_Terminal, Show_CPU, Show_GPU, Show_Memory, Show_Disk, Show_Pwsh, Show_Pkgs"
```

**Comment by jcwillox** [comment]
Ahh, we've recently migrated to a newer configuration method and changed the default config, winfetch always downloads the latest version of that config even if its meant for a newer version of winfetch. Until a new release is created, you'll have to manually grab the default config. 

@kiedtl it's probably worth creating a new release at this point, let me know if there anything still to be done?

This version of the default config is compatible with `winfetch v1.3.0`
https://github.com/lptstr/winfetch/blob/v1.3.0/lib/config.ps1

**Comment by thorstenkampe** [comment]
Thanks, that works. Although now I get  a different error (see below). It seems that winfetch is not compatible with `StrictMode` (`Set-StrictMode -Version latest`).
```
winfetch.ps1: F:\scoop\shims\winfetch.ps1:3
Line |
   3 |  … n.expectingInput) { $input | & $path  @args } else { & $path  @args }
     |                                                         ~~~~~~~~~~~~~~
     | Index was outside the bounds of the array.
```

**Comment by jcwillox** [comment]
hmm... don't use strict mode 😄

That's a separate issue as you mentioned in #40. Both `1.3.0` and the `master` version of winfetch are broken when using strict mode. I could probably make some changes to fix that. 

Interestingly that error you just posted actually appears to be caused by the scoop shim and not winfetch?

**Comment by thorstenkampe** [comment]
My mistake - I forgot that I already openend #40 for that issue.

The #40 issue is the same using the shim as when running `& $Env:SCOOP\apps\winfetch\current\winfetch.ps1`.
