### ISSUE TITLE
Error: Couldn't find manifest for 'winfetch'.

### ISSUE THREAD

**Issue by Samathingamajig** [lptstr/winfetch#42]
I installed scoop package manager like was said in the installation instructions.

Whenever I try to install winfetch with the command `scoop install winfetch`, I always get this error, no matter what terminal I use:
![image](https://user-images.githubusercontent.com/29130894/105219600-42a12100-5b1c-11eb-9ec2-77d73c558628.png)
 
If I try to run in powershell 7, I get this error instead:
![image](https://user-images.githubusercontent.com/29130894/105219827-8431cc00-5b1c-11eb-9d00-ad78b5b515a4.png)

And administrator mode returns the same errors.

**Comment by jcwillox** [comment]
This seems to be an issue with your scoop installation and not winfetch, the second image seems to provide the relevant error.

It appears you didn't change your security policy, you can try running 
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
```

Check you've followed these instructions for installing scoop
https://github.com/ScoopInstaller/Install

**Comment by Samathingamajig** [comment]
I'm still getting the "Couldn't find manifest" error even after uninstalling scoop, changing policy, reinstalling scoop.

![image](https://user-images.githubusercontent.com/29130894/105613116-21dc0400-5d86-11eb-8ec2-ec1e89bcff66.png)
![image](https://user-images.githubusercontent.com/29130894/105613121-2d2f2f80-5d86-11eb-9307-9e4c4430525b.png)

and then in a different powershell version

![image](https://user-images.githubusercontent.com/29130894/105613134-41732c80-5d86-11eb-8aba-f1f006cdb904.png)

**Comment by jcwillox** [comment]
Did you add the extras bucket?
```pwsh
scoop bucket add extras
```

**Comment by Samathingamajig** [comment]
> Did you add the extras bucket?
> 
> ```powershell
> scoop bucket add extras
> ```

that fixed it 🤦‍♂️ i must have glossed over that

and also i never saw anything about setting the execution policy when i installed scoop, before you responded

![image](https://user-images.githubusercontent.com/29130894/105624057-3e0e8e00-5de4-11eb-8fa1-efd21e759a07.png)
