### ISSUE TITLE
Support Windows XP and Vista i.e. PowerShell 2.0

### ISSUE THREAD

**Issue by mobluse** [lptstr/winfetch#45]
I think winfetch should support Windows XP and Vista i.e. PowerShell 2.0. I installed winfetch manually on Windows XP and run it from PowerShell, but it complains about "#requires" statement at line 2 for PowerShell version 5.0. I buy used computers and factory reset them, and then the OS could be XP or Vista. It would be good to be able to run winfetch to get information about the system before installing another OS.

I had to install these in order to install winfetch manually:
https://www.microsoft.com/en-US/download/details.aspx?id=16614
https://www.microsoft.com/en-US/download/details.aspx?id=16818
https://github.com/git-for-windows/git/releases/tag/v2.10.0.windows.1

The instructions for downloading didn't work in Windows XP so I had to use `git clone https://github.com/lptstr/winfetch`.

I also run winfetch 1.3.0 installed using scoop on a computer with Windows 10 20H2 and PowerShell version 5.1.19041.610.

**Comment by jcwillox** [comment]
I can see why that'd be useful, however, I don't think we should be pursuing this, PowerShell 2.0 is quite outdated now and the majority of winfetch users are likely using at least v5. It's probably not that big of an ask for users to install a newer version of PowerShell if they are using a very old machine. Supporting such an old version will likely make it harder to maintain and contribute to winfetch.

You actually don't need `git` or `scoop` to install winfetch, it's a self-contained script, so you can just download it directly. I'll add this to installation docs.
```pwsh
Invoke-WebRequest https://raw.githubusercontent.com/lptstr/winfetch/master/src/posh-winfetch.ps1 -OutFile winfetch.ps1
```

**Comment by mobluse** [comment]
I do not know of any method to install a higher version of PowerShell than 2.0 on Windows XP or Vista since Microsoft doesn't support higher versions on these OS:es. If you install Linux on the same machines you can install the latest version of PowerShell for Linux, but that isn't the OS you get when doing factory reset.

**Comment by rashil2000** [comment]
Hi @mobluse! 

Check out this repository https://github.com/Assistant/cmdfetch

It's winfetch but written in Batchfile, and supports very old systems. 

@jcwillox Actually, I have made some modifications to the above linked repository in my fork; I had this idea that maybe we can add that Batch file to this repository, just as a fallback for very old systems. What do you think?

**Comment by mobluse** [comment]
cmdfetch depends on some included exe files without source. Also there is no examples of output such as screenshots.

**Comment by rashil2000** [comment]
The only required executable is colous.exe, which is a console I/O server, and without which coloured output is not possible. You can get rid of the nircmd.exe, they are only present for taking screenshots (which you can pretty do with other methods).

The output is looks similar to [this](https://github.com/lptstr/winfetch/pull/51#issue-568731562), albeit with different information obviously.

You can try replacing all colous calls with echo calls, but then the entire output will be in a single color.

**Comment by rashil2000** [comment]
@mobluse I have made a legacy branch for old systems - https://github.com/lptstr/winfetch/tree/legacy - please use that.

**Comment by mobluse** [comment]
I will not use it since it contains colous.exe which doesn't have source code and the only information I could find about it is negative: https://greatis.com/appdata/d/Windows/c/colous.exe.htm

It is possible to color text in PowerShell 2.0. I tested examples from:
http://technet.microsoft.com/en-us/library/ff406264.aspx

**Comment by rashil2000** [comment]
Colous has been used for _years_ in console CMD programs, I have even provided a VirusTotal listing for it if you look carefully in the Readme. 

If you really want an open source alternative to colous, feel free to replace all `colous` calls with `cecho` (source code [here](https://www.codeproject.com/Articles/17033/Add-Colors-to-Batch-Files)). Send a PR too if possible.

Supporting PowerShell versions below 5.1 is out of the scope of this project.

**Comment by rashil2000** [comment]
For anyone else who stumbles upon this issue in the future, the colous dependency has been removed in https://github.com/lptstr/winfetch/commit/cc948809fbf2355fd3392fb2c1524a08774217dc from the legacy branch. 

It is recommended to use [ANSICON](https://github.com/adoxa/ansicon) (open source) instead.
