### ISSUE TITLE
Commandline params should override config

### ISSUE THREAD

**Issue by rashil2000** [lptstr/winfetch#59]
General rule of thumb is to give commandline parameters the highest preference; then the config, and then whatever is set as default in the script.

Winfetch currently ignores any commandline switch values if they have been declared in the config. This should not be the case.

Example: 
Config has: `$legacylogo = $true`
Commandline: `winfetch -legacylogo:$false`
The output still has the legacy logo.

**Comment by jcwillox** [comment]
Agreed, but I'm not sure exactly how we would implement this, basically when we execute the config we need to prevent it from re-declaring variables that already exist. Currently, I'm looking at using `Set-Variable legacylogo -Option ReadOnly` and using a `try/catch` to suppress errors when loading the config. This works but I still need a way to iterate over all the parameters, check if they exist, and set them to readonly.

**Comment by jcwillox** [comment]
Alright got it working, however, I haven't found a good way to suppress write errors when dot sourcing the config script, currently this is the best solution I've arrived at. I'll create a PR to test it soon.
```pwsh
$config = 'trap [System.Management.Automation.SessionStateUnauthorizedAccessException] { continue };' `
  + (Get-Content $configPath | Out-String) | Invoke-Expression
```
