### ISSUE TITLE
No --stdout exists

### ISSUE THREAD

**Issue by TsunayoshiSawada** [lptstr/winfetch#64]
Having a "no ascii" art flag would really really help.

**Comment by jcwillox** [comment]
Well currently there's the `-noimage` option, and there is the unreleased `-stripansi` option which should mimic neofetch's `--stdout` (`winfetch -noimage -stripansi` will produce the same effect as neofetch).

**Comment by rashil2000** [comment]
This feature is available in the upcoming release.
