### ISSUE TITLE
error: broken pipe in Alacritty

### ISSUE THREAD

**Issue by kiedtl** [lptstr/winfetch#7]
![image](https://user-images.githubusercontent.com/32681240/55726298-79588680-59dd-11e9-8a1d-bb7f3d26caf8.png)

I think this is caused by line [`323`](https://github.com/lptstr/winfetch/blob/73af19785b3ea222f327c2e7a43bed19e73044cd/src/winfetch.ps1#L323).

**Comment by TheIncorrigible1** [comment]
Suggestion: evaluate running the script with `$ErrorActionPreference = 'Stop'` or `SilentlyContinue` and check out the `$Error` object.

**Comment by kiedtl** [comment]
Noticed that this works perfectly on Arch Linux.

**Comment by kiedtl** [comment]
> Suggestion: evaluate running the script with `$ErrorActionPreference = 'Stop'` or `SilentlyContinue` and check out the `$Error` object.

I'm wondering whether this a PowerShell error, or has something to do with the way Rust handles the pipeline.

**Comment by kiedtl** [comment]
I'm suspecting that this is indeed an issue with Alacritty. Closing for now.
