### ISSUE TITLE
customization troubles

### ISSUE THREAD

**Issue by injct** [lptstr/winfetch#78]
hey, how can i do this? (the custom picture and add bars for cpu usage, memory, and the disks? also i am having trouble adding multipole disks. thanks!)

![image](https://user-images.githubusercontent.com/82984981/115637455-2d37c080-a2de-11eb-9bc0-999871a2af2c.png)

**Comment by rashil2000** [comment]
Hey, our Wiki [page](https://github.com/lptstr/winfetch/wiki/Configuration) has all the details on how to customize the output of Winfetch, be sure to experiment with all the options! 

Note that if you are versions less than or equal to 2.0.0, you'll need to have Imagemagick installed and in your **Path**.

**Comment by injct** [comment]
i tried that, and nothing really helped. is there a more in-depth version? i just want a custom image and the bars. 
![image](https://user-images.githubusercontent.com/82984981/115651596-79dcc500-a2f9-11eb-82de-6a708f4f886a.png)
i have tried messing with this setting to get a custom image and it was not working. which folder do i put the photo in? i tried using some imagemagick guides and nothing helped :/ (i have it installed)

**Comment by rashil2000** [comment]
Do you mind sharing your config file? I'd like to see what's happening.

**Comment by injct** [comment]
[winfetch.txt](https://github.com/lptstr/winfetch/files/6361947/winfetch.txt)
i put it in .txt because i couldnt upload .ps1

**Comment by jcwillox** [comment]
That's just the script itself, your config file will be stored at `C:\Users\YourName\.config\winfetch\config.ps1` thats the one you should be editing. If you want to add an image uncomment the `# $image...` line and put in the path to an image on your machine.

```pwsh
# ===== WINFETCH CONFIGURATION =====
$image = "C:\Users\YourName\Pictures\MyCoolPicture.png"
```

as for the bars you can again uncomment (remove the `#` symbol) these lines and set the values to how you want them to display

```pwsh
# Configure how to show info for levels
# Default is for text only.
# 'bar' is for bar only.
# 'textbar' is for text + bar.
# 'bartext' is for bar + text.
$cpustyle = 'bar'
$memorystyle = 'textbar'
$diskstyle = 'bartext'
$batterystyle = 'bartext'
```

the configuration file contains examples and explainations of all the available configuration options

**Comment by injct** [comment]
i couldnt find the config path and didnt want it to be reset. thank you though! that is exactly what i needed.
