### ISSUE TITLE
Broken on Windows 7 with colors

### ISSUE THREAD

**Issue by E404NNF** [lptstr/winfetch#82]
I installed winfetch through scoop on Windows 7, the output isn't really like what's expected, maybe Powershell 5.1 on win 7 doesn't support the colors winfetch uses? it works with neofetch and neofetch-win

![image](https://user-images.githubusercontent.com/37207067/120098712-c3f66900-c137-11eb-963c-1a865b1f2b0c.png)

**Comment by rashil2000** [comment]
Which terminal are you using for winfetch and neofetch?

**Comment by E404NNF** [comment]
> 
> 
> Which terminal are you using for winfetch and neofetch?

Powershell in the directory `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe`

**Comment by rashil2000** [comment]
That's not the terminal, that's the location to the PowerShell executable...
But if you're launching PowerShell by double clicking in that location, it must be opening in the default Windows 7 terminal, which is called conhost. And conhost in Windows 7 does not support ANSI escape sequences. You have three options:
- use winfetch with `-s` flag, like `winfetch -s`, this will remove those sequences but you will not have any colors.
- use some other terminal like ConEmu
- search for how to enable ANSI support in conhost.

The third method is very hacky and not recommended.
I'd recommend you to use ConEmu.

**Comment by E404NNF** [comment]
> 
> 
> That's not the terminal, that's the location to the PowerShell executable...
> But if you're launching PowerShell by double clicking in that location, it must be opening in the default Windows 7 terminal, which is called conhost. And conhost in Windows 7 does not support ANSI escape sequences. You have three options:
> 
>     * use winfetch with `-s` flag, like `winfetch -s`, this will remove those sequences but you will not have any colors.
> 
>     * use some other terminal like ConEmu
> 
>     * search for how to enable ANSI support in conhost.
> 
> 
> The third method is very hacky and not recommended.
> I'd recommend you to use ConEmu.

ok thank you!

**Comment by rashil2000** [comment]
A [wiki article](https://github.com/lptstr/winfetch/wiki/ANSI-Colors) has been created for anyone else who faces this issue.
